services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: seth-clinic-db
    environment:
      POSTGRES_DB: seth_clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - seth-clinic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for job queue and caching
  redis:
    image: redis:7-alpine
    container_name: seth-clinic-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - seth-clinic-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB for unstructured data and analytics
  mongodb:
    image: mongo:7.0
    container_name: seth-clinic-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: seth_clinic_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - seth-clinic-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: seth-clinic-backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/seth_clinic
      MONGODB_URL: mongodb://admin:${MONGODB_PASSWORD:-admin123}@mongodb:27017/seth_clinic_mongo?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-super-secret-refresh-key-change-in-production}
      LOG_LEVEL: debug
      # SHA configuration
      SHA_API_URL: ${SHA_API_URL:-https://api.sha.go.ke}
      SHA_PROVIDER_CODE: ${SHA_PROVIDER_CODE:-CLINIC001}
      SHA_FACILITY_LEVEL: ${SHA_FACILITY_LEVEL:-2}
      SHA_SUBMISSION_TIMEOUT_MS: ${SHA_SUBMISSION_TIMEOUT_MS:-30000}
      SHA_REQUIRE_INVOICE_BEFORE_SUBMISSION: ${SHA_REQUIRE_INVOICE_BEFORE_SUBMISSION:-true}
      SHA_AUTO_SUBMIT_CLAIMS: ${SHA_AUTO_SUBMIT_CLAIMS:-false}
      SHA_PAYMENT_CHECK_INTERVAL_HOURS: ${SHA_PAYMENT_CHECK_INTERVAL_HOURS:-24}
      SHA_EXPORT_RETENTION_DAYS: ${SHA_EXPORT_RETENTION_DAYS:-90}
      SHA_DOCUMENT_MAX_SIZE_MB: ${SHA_DOCUMENT_MAX_SIZE_MB:-10}
      SHA_BATCH_SIZE_LIMIT: ${SHA_BATCH_SIZE_LIMIT:-100}
      # M-Pesa configuration
      MPESA_CONSUMER_KEY: ${MPESA_CONSUMER_KEY:-}
      MPESA_CONSUMER_SECRET: ${MPESA_CONSUMER_SECRET:-}
      MPESA_SHORTCODE: ${MPESA_SHORTCODE:-}
      MPESA_PASSKEY: ${MPESA_PASSKEY:-}
      MPESA_BASE_URL: ${MPESA_BASE_URL:-https://sandbox.safaricom.co.ke}
      MPESA_CALLBACK_URL: ${MPESA_CALLBACK_URL:-}
      # Email configuration
      SENDGRID_API_KEY: ${SENDGRID_API_KEY:-}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@sethclinic.com}
      # File storage
      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      STORAGE_PATH: ${STORAGE_PATH:-./uploads}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads
      - exports_data:/app/exports
    networks:
      - seth-clinic-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: npm run dev

  # Background Worker
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: seth-clinic-worker
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/seth_clinic
      MONGODB_URL: mongodb://admin:${MONGODB_PASSWORD:-admin123}@mongodb:27017/seth_clinic_mongo?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      LOG_LEVEL: debug
      # SHA configuration for worker
      SHA_API_URL: ${SHA_API_URL:-https://api.sha.go.ke}
      SHA_PROVIDER_CODE: ${SHA_PROVIDER_CODE:-CLINIC001}
      SHA_PAYMENT_CHECK_INTERVAL_HOURS: ${SHA_PAYMENT_CHECK_INTERVAL_HOURS:-24}
      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      STORAGE_PATH: ${STORAGE_PATH:-./uploads}
      # Currency configuration
      DEFAULT_CURRENCY: ${DEFAULT_CURRENCY:-KES}
      CURRENCY_LOCALE: ${CURRENCY_LOCALE:-en-KE}
      CURRENCY_SYMBOL: ${CURRENCY_SYMBOL:-KES}
    command: npm run worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads
      - exports_data:/app/exports
    networks:
      - seth-clinic-network

  # Frontend (Next.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: seth-clinic-frontend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5000/api}
      NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION:-1.0.0}
      NEXT_PUBLIC_ENVIRONMENT: ${NODE_ENV:-development}
      # Currency configuration
      NEXT_PUBLIC_DEFAULT_CURRENCY: ${DEFAULT_CURRENCY:-KES}
      NEXT_PUBLIC_CURRENCY_LOCALE: ${CURRENCY_LOCALE:-en-KE}
      NEXT_PUBLIC_CURRENCY_SYMBOL: ${CURRENCY_SYMBOL:-KES}
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - seth-clinic-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  uploads_data:
  exports_data:

networks:
  seth-clinic-network:
    driver: bridge
